# fly.toml app configuration file generated for julius-fitness-gym

app = 'julius-fitness-gym-r1ds5g'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'
  target = 'production'

[env]
  CONTAINER_ROLE = 'web'
  PORT = '8080'
  APP_ENV = 'production'
  APP_DEBUG = 'false'
  APP_URL = 'https://www.juliusgym.ro'
  APP_LOCALE = 'ro'
  APP_FALLBACK_LOCALE = 'en'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  DB_CONNECTION = 'pgsql'
  SESSION_DRIVER = 'database'
  GITHUB_REDIRECT_URI = 'https://www.juliusgym.ro/auth/github/callback'
  MAIL_MAILER = 'resend'
  MAIL_FROM_ADDRESS = 'noreply@juliusgym.ro'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
